<?php
/* set default val */
if ( ! function_exists( 'innovation_ruby_redux_default_val' ) ) {
	function innovation_ruby_redux_default_val() {
		return array(
			'main_site_layout'                     => 'is-full-width',
			'site_background'                      => array(
				'background-color'      => '#fff',
				'background-size'       => 'cover',
				'background-attachment' => 'fixed',
				'background-position'   => 'left top',
				'background-repeat'     => 'no-repeat'
			),
			'site_background_link'                 => '',
			'site_container_width'                 => 1200,
			'site_smooth_scroll'                   => 0,
			'site_smooth_display'                  => 0,
			'site_smooth_display_style'            => 'ruby-zoom',
			'page_pagination_style'                => 'standard',
			'simple_page_pagination'               => 0,
			'retina_support'                       => 0,
			'start_views'                          => 0,
			'touch_tooltip'                        => 1,
			'open_graph'                           => 1,
			'thumb_pattern'                        => 1,
			'thumb_holder'                         => 1,
			'category_bar'                         => 1,
			'post_meta_info_manager'               => array(
				'enabled'  => array(
					'author' => 'Author',
					'date'   => 'Date'
				),
				'disabled' => array(
					'cate'    => 'Category',
					'tag'     => 'Tags',
					'view'    => 'View',
					'comment' => 'Comment'
				)
			),
			'post_format_icon'                     => 1,
			'post_header_center_text'              => 0,
			'post_share_bar'                       => 1,
			'right_social_bar_el'                  => 'comment',
			'classic_share_bar_position'           => 'relative',
			'grid_share_bar_position'              => 'relative',
			'list_share_bar_position'              => 'relative',
			'grid_excerpt_length'                  => 25,
			'small_grid_excerpt_length'            => 20,
			'list_excerpt_length'                  => 35,
			'classic_summary_type'                 => 1,
			'classic_excerpt_length'               => 100,
			'site_readmore_text'                   => 'read more',
			'review_score_icon'                    => 1,
			'review_score_intro'                   => 1,
			'score_intro_1'                        => 'tech score',
			'score_intro_2'                        => 'tech score',
			'score_intro_3'                        => 'tech score',
			'score_intro_4'                        => 'tech score',
			'sticky_navigation'                    => 1,
			'main_nav_social_icon'                 => 1,
			'main_nav_social_icon_color'           => 0,
			'main_nav_search_icon'                 => 1,
			'aside_header_nav_icon'                => 1,
			'main_nav_background'                  => '',
			'main_navigation_height'               => '72',
			'main_sticky_navigation_height'        => '48',
			'main_nav_el_border'                   => array(
				'color' => '#fff',
				'alpha' => 0.1
			),
			'main_nav_shadow'                      => 0,
			'main_sub_nav_background'              => '',
			'main_sub_nav_shadow'                  => 1,
			'mega_menu_cate_text_style'            => 'is-dark-text',
			'header_style'                         => '1',
			'header_second_layout_manager'         => array(
				'enabled'  => array(
					'logo_section' => 'Logo Section',
					'nav_bar'      => 'Navigation'
				),
				'disabled' => array()
			),
			'header_second_logo_section_height'    => '240',
			'header_second_logo_position'          => 'center',
			'header_url_ads_right_banner'          => '',
			'header_second_logo_section_bg'        => array(
				'background-color'      => '#ffffff',
				'background-size'       => 'cover',
				'background-attachment' => 'fixed',
				'background-position'   => 'center center',
				'background-repeat'     => 'no-repeat'
			),
			'header_second_bottom_margin'          => '',
			'aside_header_social_bar'              => 1,
			'aside_header_widget_section'          => 1,
			'aside_header_close_button'            => 1,
			'aside_header_close_button_mobile'     => 1,
			'header_ads_type'                      => 1,
			'header_url_ads'                       => '',
			'site_sidebar_position'                => 'right',
			'innovation_ruby_multi_sidebar'        => array(),
			'sticky_sidebar'                       => 0,
			'footer_style'                         => '1',
			'footer_social_bar'                    => 1,
			'footer_background'                    => array(
				'background-color'      => '#282828',
				'background-size'       => 'cover',
				'background-attachment' => 'fixed',
				'background-position'   => 'center center',
				'background-repeat'     => 'no-repeat'
			),
			'fixed_footer'                         => 0,
			'footer_text_style'                    => 'is-light-text',
			'fixed_footer_mobile'                  => 0,
			'site_copyright_bg_color'              => '#282828',
			'site_copyright'                       => '',
			'site_back_to_top'                     => 1,
			'site_back_to_top_mobile'              => 0,
			'featured_style'                       => 'none',
			'featured_sort'                        => 'date_post',
			'featured_num'                         => 5,
			'featured_offset'                      => 0,
			'big_post_first'                       => 1,
			'home_layout'                          => 'classic-layout',
			'unique_post'                          => 0,
			'home_sidebar'                         => 'innovation_ruby_sidebar_default',
			'home_sidebar_position'                => 'default',
			'default_single_post_layout'           => 'is_classic',
			'single_post_meta_info_manager'        => array(
				'enabled'  => array(
					'cate'    => 'Category',
					'author'  => 'Author',
					'date'    => 'Date',
					'comment' => 'Comment',
					'tag'     => 'Tags',
					'view'    => 'View'
				),
				'disabled' => array()
			),
			'default_single_post_first_paragraph'  => 'none',
			'default_single_review_box_position'   => 'left_top',
			'popup_gallery'                        => 1,
			'single_popup_image'                   => 1,
			'default_single_post_sidebar'          => 'innovation_ruby_sidebar_default',
			'default_single_post_sidebar_position' => 'default',
			'single_max_content_width'             => 800,
			'single_navigation_box'                => 1,
			'single_author_box'                    => 1,
			'enable_website_comment_box'           => 0,
			'single_related_box'                   => 1,
			'single_related_where'                 => 'all',
			'single_related_number_of_post'        => 5,
			'single_top_share_social'              => 1,
			'single_bottom_share_social'           => 0,
			'single_aside_share_social'            => 1,
			'social_like_post'                     => 0,
			'default_single_page_title'            => 1,
			'default_single_page_sidebar'          => 'innovation_ruby_sidebar_default',
			'default_single_page_sidebar_position' => 'default',
			'page_max_content_width'               => 800,
			'default_single_page_comment_box'      => 1,
			'author_layouts'                       => 'classic-layout',
			'author_sidebar'                       => 'innovation_ruby_sidebar_default',
			'author_sidebar_position'              => 'default',
			'search_layouts'                       => 'classic-layout',
			'search_sidebar'                       => 'innovation_ruby_sidebar_default',
			'search_sidebar_position'              => 'default',
			'archive_layouts'                      => 'classic-layout',
			'archive_sidebar'                      => 'innovation_ruby_sidebar_default',
			'archive_sidebar_position'             => 'default',
			'share_to_facebook'                    => 1,
			'share_to_twitter'                     => 1,
			'share_to_pinterest'                   => 1,
			'share_to_linkedin'                    => 0,
			'share_to_tumblr'                      => 0,
			'share_to_vk'                          => 0,
			'site_social'                          => 1,
			'body_font'                            => array(
				'font-family' => 'Raleway',
				'google'      => true,
				'font-size'   => '14px',
				'line-height' => '24px',
				'font-weight' => '400',
				'color'       => '#333'
			),
			'post_excerpt_font_size'               => '13',
			'medium_post_title_font'               => array(
				'font-family'    => 'Raleway',
				'font-size'      => '18px',
				'text-transform' => 'capitalize',
				'google'         => true,
				'font-weight'    => '700',
				'color'          => '#282828'
			),
			'small_post_title_font_size'           => '14',
			'big_post_title_font_size'             => '26',
			'single_post_title_font_size'          => '36',
			'meta_info_font'                       => array(
				'font-size'      => '10px',
				'google'         => true,
				'font-weight'    => '400',
				'color'          => '#777',
				'font-family'    => 'Lato',
				'text-transform' => 'uppercase',
				'letter-spacing' => '1px'
			),
			'cate_bar_font'                        => array(
				'font-size'      => '10px',
				'google'         => true,
				'font-weight'    => '700',
				'font-family'    => 'Lato',
				'text-transform' => 'uppercase',
				'letter-spacing' => '2px'
			),
			'read_more_font'                       => array(
				'font-size'      => '10px',
				'google'         => true,
				'font-weight'    => '400',
				'font-family'    => 'Lato',
				'text-transform' => 'uppercase',
				'letter-spacing' => '2px'
			),
			'main_nav_font'                        => array(
				'font-family'    => 'Raleway',
				'font-size'      => '12px',
				'letter-spacing' => '2px',
				'font-weight'    => '600',
				'text-transform' => 'uppercase',
				'google'         => true
			),
			'main_sub_nav_font'                    => array(
				'font-family'    => 'Raleway',
				'font-size'      => '10px',
				'letter-spacing' => '1px',
				'font-weight'    => '600',
				'text-transform' => 'uppercase',
				'google'         => true
			),
			'widget_header_font'                   => array(
				'font-family'    => 'Raleway',
				'font-size'      => '12px',
				'color'          => '#282828',
				'google'         => true,
				'font-weight'    => '600',
				'letter-spacing' => '1px',
				'text-transform' => 'uppercase'
			),
		);
	}
}
